spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  cloud:
    bus:
      enabled: true

# --- Monitoring and Health Configuration ---
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
