spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  cloud:
    bus:
      enabled: true

# --- Eureka Server Specific Configuration ---
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

# --- Monitoring and Health Configuration ---
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# --- Info Endpoint Configuration ---
info:
  app:
    name: ${spring.application.name}
    description: "Easycom Config Management Microservice"
    version: "1.0.0"
