# --- Spring Global Configuration ---
spring:

  # --- Message Broker Configuration ---
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

# --- Eureka Server Specific Configuration ---
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

# --- Monitoring and Health Configuration ---
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
