users:
  message: "Welcome to Library User Management local APIs"
  contactDetails:
    name: "User Team - Identity Dept"
    email: "users-support@library.com"
  onCallSupport:
    - (555) 111-2222

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Base de données Users
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  liquibase:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
